#!/bin/bash

echo "🔍 Диагностика проблем на VPS..."

echo ""
echo "📋 Пошаговая диагностика:"
echo ""
echo "1. 🔍 Проверьте, что вы находитесь в правильной папке:"
echo "   pwd"
echo "   # Должно показать: /var/www/html/nord-laundry-telegram-bot"
echo ""
echo "2. 📁 Проверьте содержимое папки:"
echo "   ls -la"
echo "   # Должны быть файлы: package.json, bot-runner.mjs, .env"
echo ""
echo "3. 📦 Проверьте, есть ли архив:"
echo "   ls -la whatsapp_auth_*.tar.gz"
echo "   # Если файла нет, значит он не был загружен"
echo ""
echo "4. 📤 Если архива нет, загрузите его с локальной машины:"
echo "   # На локальной машине выполните:"
echo "   scp whatsapp_auth_20251010_121550.tar.gz root@YOUR_VPS_IP:/var/www/html/nord-laundry-telegram-bot/"
echo ""
echo "5. ✅ Проверьте права доступа:"
echo "   ls -la whatsapp_auth_20251010_121550.tar.gz"
echo "   # Файл должен быть доступен для чтения"
echo ""
echo "6. 🔄 Распакуйте архив:"
echo "   tar -xzf whatsapp_auth_20251010_121550.tar.gz"
echo ""
echo "7. 📊 Проверьте результат:"
echo "   ls -la .wwebjs_auth/"
echo "   # Должна появиться папка .wwebjs_auth"
echo ""
echo "8. 🚀 Запустите бота:"
echo "   npm start"
echo ""
echo "❌ Частые ошибки и решения:"
echo ""
echo "Ошибка: 'No such file or directory'"
echo "Решение: Архив не загружен на VPS"
echo "Команда: scp whatsapp_auth_20251010_121550.tar.gz root@YOUR_VPS_IP:/var/www/html/nord-laundry-telegram-bot/"
echo ""
echo "Ошибка: 'Permission denied'"
echo "Решение: Неправильные права доступа"
echo "Команда: chmod 644 whatsapp_auth_20251010_121550.tar.gz"
echo ""
echo "Ошибка: 'tar: Child returned status 2'"
echo "Решение: Поврежденный архив или неправильный путь"
echo "Команда: file whatsapp_auth_20251010_121550.tar.gz"
echo ""
echo "💡 Альтернативный способ загрузки через SFTP:"
echo "1. sftp root@YOUR_VPS_IP"
echo "2. cd /var/www/html/nord-laundry-telegram-bot/"
echo "3. put whatsapp_auth_20251010_121550.tar.gz"
echo "4. exit"
echo "5. tar -xzf whatsapp_auth_20251010_121550.tar.gz"
